### PR TITLE
code editors - introduction to vscode and vim

### PR DESCRIPTION
**Pull request by evamo0508**
This PR includes two changes -
1. Modify the path of my previous PR page - `tools/gazebo-simulation` since I found that the link is not working on the website.
2. A new page under `tools` - code editors: Introduction to VS Code and Vim.

### CODE REVIEW

**Comment by smbryan** [comment]
Looks almost ready to go. However, I don't think that the images will work in the current directory. They should be wiki/tools/assets and not the top-level assets.

**Comment by smbryan** [comment]
@evamo0508, I can't merge this until you move the assets to the appropriate directory.

**Comment by evamo0508** [comment]
Hi @smbryan , sorry I missed the email earlier. Fixed the problem and it should be good to go! thanks.

**Comment by smbryan** [comment]
Solid. Enjoy your break!

**Pull request merged**
