### PR TITLE
MRSD 2022 Team C Wiki Entry Submission.

### PR DESCRIPTION
**Pull request by jasonxiang1**
Created and Actuation article about MoveIt and HEBI setup and integration in ROS. Added a number of MoveIt setup assistant images in the Actuation assets folder.

### CODE REVIEW

**Comment by smbryan** [comment]
@jasonxiang1, this looks very close to being ready to merge. However, I'm not seeing an update to the navigation page.

**Comment by jasonxiang1** [comment]
Hey Sean,

Apologies. I thought I changed the navigation.yaml file. Should I close this and submit a new pull request with the updated navigation.yaml change?

**Comment by smbryan** [comment]
@jasonxiang1 just add your updates and push. It'll pop up here.

**Comment by jasonxiang1** [comment]
Just updated the pull request. Let me know if you have any problems or questions.

**Comment by smbryan** [comment]
Merged. Good luck with finals!

**Pull request merged**
