### PR TITLE
Team G, MRSD 2023 : Added wiki entry for Hello Robot to common-platforms 

### PR DESCRIPTION
**Pull request by PallaviMadhukar**

### CODE REVIEW

**Comment by gbrueggman** [comment]
Missing the date/title table at top. Missing See Also section content

**Review by nevalsar — CHANGES_REQUESTED** [review]
(See earlier review comments)

**Review by nevalsar — APPROVED** [review]
Approving to unblock.

**Comment by nevalsar** [comment]
Contributor not responsive - will copy over to a new MR to resolve conflicts and merge.

**Pull request closed without merging**
