### PR TITLE
Create husky_interfacing_procedure

### PR DESCRIPTION
**Pull request by ahemaesh**
Moved the husky_setup_procedure to common_platforms as per #38

### CODE REVIEW

**Comment by benbo** [comment]
@ahemaesh The link on the landing page to Husky Interfacing Procedure is broken.

**Comment by ahemaesh** [comment]
Hi Ben,

The article is available at https://github.com/RoboticsKnowledgebase/roboticsknowledgebase.github.io/blob/master/wiki/common-platforms/Husky_interfacing_and_communication.md

I’ll look further into the webpage being inaccessible from the Wiki,

Regards,
Avinash

**Comment by smbryan** [comment]
@ahemaesh, the filename needs to be `husky_interfacing_and_communication.md` not `Husky_interfacing_and_communication.md`. @benbo, thank you for catching that.

**Comment by ahemaesh** [comment]
Hi Bryan,

I addressed the issue and created new pull request.

Thanks,
Avinash

**Comment by ahemaesh** [comment]
Hi Bryan,
Thank you for merging the pull request in the master 😊

Hi Ben,
The link is working now.

Thanks,
Avinash


From: Avinash Hemaeshwara Raju <ahemaesh@andrew.cmu.edu>
Date: Tuesday, May 14, 2019 at 11:11 AM
To: "RoboticsKnowledgebase/roboticsknowledgebase.github.io" <reply@reply.github.com>, "RoboticsKnowledgebase/roboticsknowledgebase.github.io" <roboticsknowledgebase.github.io@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [RoboticsKnowledgebase/roboticsknowledgebase.github.io] Create husky_interfacing_procedure (#41)

Hi Ben,

The article is available at https://github.com/RoboticsKnowledgebase/roboticsknowledgebase.github.io/blob/master/wiki/common-platforms/Husky_interfacing_and_communication.md

I’ll look further into the webpage being inaccessible from the Wiki,

Regards,
Avinash

**Pull request merged**
