### PR TITLE
Team C F22: Task Prioritization Control

### PR DESCRIPTION
**Pull request by anthonykyu**
Added new wiki entry on task prioritization control for advanced manipulator control

### CODE REVIEW

**Comment by smbryan** [comment]
@nevalsar, this looks ready to merge once the TAs are done.

**Review by nevalsar — APPROVED** [review]

**Comment by nevalsar** [comment]
@anthonykyu There are other changes made in `navigation.yml` that is conflicting with this branch's changes. Please update the PR (merge from master  / rebase).

**Review by nevalsar — CHANGES_REQUESTED** [review]
@anthonykyu There are other changes made in `navigation.yml` that is conflicting with this branch's changes. Please update the PR (merge from master / rebase).

**Comment by anthonykyu** [comment]
@nevalsar I have made the change. It seems that the merge conflict was from another PR adding to the same wiki section. My new commit should've resolved it.

**Review by nevalsar — APPROVED** [review]

**Pull request merged**
