### PR TITLE
Team I Wiki Entry

### PR DESCRIPTION
**Pull request by Geniussh**
Added to the existing entry ```ROS Mapping and Localization``` by providing a detailed tutorial on how to set up an odometry system (IMU + encoder) and to get a filtered and smoothed odometry using the ```robot_localization``` package in Gazebo.

### CODE REVIEW

**Comment by smbryan** [comment]
This looks like a great update. However, we do need to scratch the HTML in there before we merge it in.

**Comment by Geniussh** [comment]
> This looks like a great update. However, we do need to scratch the HTML in there before we merge it in.

Could you elaborate on "scratch the HTML"? Is it that the website won't support the collapse/expand of the html code?

**Comment by Geniussh** [comment]
I just removed the HTML warpping around the code snippets. Let me know if this is what's expected.

**Comment by smbryan** [comment]
You got it. Thank you.

**Pull request merged**
