### PR TITLE
Tutorial on GPU system setup for computer vision and deep learning

### PR DESCRIPTION
**Pull request by heethesh**
The tutorial is actively maintained by me at [https://github.com/heethesh/Computer-Vision-and-Deep-Learning-Setup/](https://github.com/heethesh/Computer-Vision-and-Deep-Learning-Setup/) for around a year and hope it will be helpful for others too.

### About
This tutorial will help you setup your Ubuntu (16/17/18) system with a NVIDIA GPU including installing the Drivers, CUDA, cuDNN, and TensorRT libraries. Tutorial also covers on how to build OpenCV from source and installing Deep Learning Frameworks such as TensorFlow (Source Build), PyTorch, Darknet for YOLO, Theano, and Keras.

### CODE REVIEW

**Comment by smbryan** [comment]
This is a solid contribution. However, I'd like to include the full tutorial in our repository. 

If you're concerned about attribution, how about we include a "References" link to your repository as a footnote?

**Comment by heethesh** [comment]
Yes, that should be fine, not a problem! I have updated this PR to include the full tutorial.

**Comment by benbo** [comment]
@smbryan do you think this contribution is ready to be merged?

**Comment by smbryan** [comment]
@benbo, thanks for the follow up! @heethesh, I overlooked your update. Merging this in now.

**Comment by benbo** [comment]
@heethesh the images you link aren't loading. They are pointing to your GitHub. Could you fix this please? @smbryan we could open an issue for this.

**Comment by smbryan** [comment]
Done. Please see #29.

**Pull request merged**
